version: "3"
services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:  
    image: mongo
    ports:
      - "27017:27017"